languageCode = "ja"
hasCJKLanguage = true
paginatePath = ""
pluralizeListTitles = false
enableGitInfo = true
enableRobotsTXT = true

baseURL = "https://ress.39.gy/"
theme = "PaperMod"

title = "Ress Profile"

[params]
env = "production"
defaultTheme = "auto"
comments = true
ShowReadingTime = true
ShowShareButtons = true

title = "Ress Profile"
description = "情報学科に所属する大学生です"
#images = "<link or path of image for opengraph, twitter-cards>"
author = "Ress"

[params.profileMode]
enabled = true
title = "Ress"
imageUrl = "/img/avatar.png"

[[params.profileMode.buttons]]
name = "About Me"
url = "/about/"
weight = 1

[[params.profileMode.buttons]]
name = "Posts"
url = "/posts/"
weight = 2

[[params.socialIcons]]
name = "Blog"
url = "https://www.39.gy/"
weight = 1

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/ress997"
weight = 2

[[params.socialIcons]]
name = "github"
url = "https://github.com/ress997"
weight = 3

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Archives"
url = "/archives/"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3

[taxonomies]
tag = "tags"

[minify]
disableXML = true
minifyOutput = true
