languageCode = "ja"
enableGitInfo = true
hasCJKLanguage = true
pluralizeListTitles = false
paginatePath = ""
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

baseURL = "https://profile.39.gy/"
theme = "hallo"

title = "Ress Profile"
googleAnalytics = "UA-128645055-3"

[Author]
name = "Ress"

#[params.colors]
#background = "#81c6ff"
#foreground = "#edf7ff"
#hover = "#ffba82"

[[params.links]]
icon = "twitter"
title = "Twitter"
url = "https://twitter.com/@ress997"

[[params.links]]
icon = "mastodon"
title = "Fumi"
url = "https://fumi.39.gy/@ress"

[[params.links]]
icon = "mastodon"
title = "yukari.cafe"
url = "https://yukari.cafe/@ress"

[[params.links]]
icon = "mastodon"
title = "social.minecraft.ooo"
url = "https://social.minecraft.ooo/@ress"

[[params.links]]
icon = "mastodon"
title = "kancolle.social"
url = "https://kancolle.social/@ress"

[[params.links]]
iconset = "fas"
icon = "id-badge"
title = "Portfolio"
url = "https://x39.dev/"

[[params.links]]
icon = "wordpress-simple"
title = "Blog"
url = "https://blog.39.gy/"
