name: Build and Deploy
on:
  push:
  pull_request:
  repository_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download theme
        uses: actions/checkout@v2
        with:
          repository: EmielH/hallo-hugo
          path: themes/hallo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Save /public
        uses: actions/upload-artifact@v1
        with:
          name: public
          path: public

  deploy:
    name: Deploy
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Load /public
        uses: actions/download-artifact@v1
        with:
          name: public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
